import { CreateSubTaskDto } from '@/sub-tasks/dto/create-sub-task.dto';
import { SubTaskEntity } from '@/sub-tasks/entities/sub-task.entity';

export const subTaskGenerator = (
  differenceDays: number,
  taskStartDate: string,
  taskTitle: string,
) => {
  const autoSubTasks = Array.from({ length: differenceDays + 1 }, (_, i) => {
    const autoSubTaskPayload: CreateSubTaskDto = {
      title: taskTitle,
    };
    const newAutoSubtask = new SubTaskEntity(autoSubTaskPayload);
    newAutoSubtask.relatedDate = new Date(
      new Date(taskStartDate).setHours(
        new Date(taskStartDate).getHours() + i * 24,
      ),
    )
      .toISOString()
      .split('T')[0];
    newAutoSubtask.isAutoGenerated = true;

    return newAutoSubtask;
  });
  return autoSubTasks;
};
